USE GUESTBOOK;

DROP TABLE IF EXISTS GMUSER;
#게임계정
CREATE TABLE GMUSER
(
	ID_GMUSER INT NOT NULL auto_increment PRIMARY KEY, #계정IDX(PK)
    USER_ID   VARCHAR(30) NOT NULL,                    #계정ID(UK1)
    USER_PWD  VARCHAR(30) NOT NULL                     #계정비밀번호
);

ALTER TABLE GMUSER
ADD CONSTRAINT UK1_GMUSER UNIQUE(USER_ID);

INSERT INTO GMUSER(USER_ID,USER_PWD)VALUES('junios','1234');
INSERT INTO GMUSER(USER_ID,USER_PWD)VALUES('wjlee','4567');

SELECT * FROM GMUSER;


SELECT COUNT(1) FROM GMUSER WHERE USER_ID = 'wjlee';

SELECT COUNT(1) FROM GMUSER WHERE USER_ID = 'junios' AND USER_PWD = '1234';

